---
- name: Convert podcast.vars into OPML format
  hosts: localhost
  vars_files:
    - vars/podcasts.yml
  vars: 
    podfile: files/podcasts.opml
  tasks:
    - name: create opml file
      file:
        path: "{{ podfile }}"
        state: touch

    - name: Write OPML header
      blockinfile:
        path: "{{ podfile }}"
        marker: "# {mark} starting block"
        block: |
          <opml>
          <head/>
          <body>

    - name: Write OPML Body
      lineinfile:
        path: "{{ podfile }}"
        insertafter: <outline title="Castget OPML subscription file" text="Subbed pods">
        line: <outline title="{{ item.key }}" type="rss" htmlUrl="{{ item.value }} />"
      loop: "{{ podcasts | dict2items }}"

    - name: Write OPML Footer
      blockinfile:
        marker: " # {mark} ending block"
        path: "{{ podfile }}"
        block: |
          </body>
          </opml>
